service: serverless-alexa-skill-quizlet

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  answer:
    handler: handler.answer
    events:
      - alexaSkill

package:
  exclude:
    - node_modules/**